### ISSUE TITLE
Support for default lambdas

### ISSUE THREAD

**Issue by RickMeasham** [aachurin/peewee_migrations#10]
The `default` parameter in a peewee field definition lets me specify a function that's called to set the default value. This can be a lambda function. However it appears this gets referenced by name when creating a migration, and thus becomes `<lambda>` in the migration file which is a syntax error.

This works for peewee:

    expires_utc = DateTimeField(default=lambda: datetime.datetime.now() + datetime.timedelta(hours=1))

But `pem watch` turns this into this in the migration and blows up:

    expires_utc = DateTimeField(default=models.user.<lambda>)

The stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee_migrations/cli.py", line 255, in watch
    result = router.create(tracecode=context)
  File "/usr/local/lib/python3.8/dist-packages/peewee_migrations/migrator.py", line 620, in create
    new_snap = self.storage.exec(compiler.module_code)['snapshot']
  File "/usr/local/lib/python3.8/dist-packages/peewee_migrations/migrator.py", line 518, in exec
    code = compile(code, '<string>', 'exec', dont_inherit=True)
  File "<string>", line 31
    expires_utc = DateTimeField(default=models.user.<lambda>)
```

Might be solvable using `inspect`?:

    import inspect
    inspect.getsource(myfunc)

**Comment by aachurin** [comment]
No, you should not use lambdas.
Use named functions.

**Comment by RickMeasham** [comment]
Lambdas work for Peewee. I'm OK if there's a reason for not using them, but just saying "don't use them" isn't very useful. Creating named functions rather than using lamdas is ignoring one of the fundamental patterns of python.
