### ISSUE TITLE
merged_orm to help in migrating data from one column to another

### ISSUE THREAD

**Issue by GothAck** [aachurin/peewee_migrations#12]
Would be useful to have a third parameter, merged_orm, passed to forward and backward functions that would allow easier migrations between columns that have changed names and datatypes in the migration process, basically the sum of fields of both old_orm and new_orm. Would this be feasible?

For example it's currently seemingly not possible to do:
```py
new_table.update({new_table.org_id: old_table.account_id})
```
but would be possible to do if we had a merged schema containing both the old and new fields:
```py
merged_table.update({merged_table.org_id: merged_table.account_id})
```

**Comment by aachurin** [comment]
In fact new_orm and old_orm are already merged state.
Data migration occurs before deleting real columns from the table.
If the table is the same then everything works.
If the tables are different, then of course this will not work.
