### ISSUE TITLE
allow independent execution of migration scripts.

### ISSUE THREAD

**Issue by mridulganga** [aachurin/peewee_migrations#13]
I have a database which has tables already created. I want to skip the first migration, but not able to. If I run the 2nd migration, it still tries and fails while creating the table. Is there any way to skip the table creation part and only do the alter table commands?

**Comment by aachurin** [comment]
Hi! You should use --fake key to skip first migration.

вт, 29 сент. 2020 г., 03:11 Mridul Ganga <notifications@github.com>:
