### ISSUE TITLE
`forward` migration: new table does not exist

### ISSUE THREAD

**Issue by RickMeasham** [aachurin/peewee_migrations#15]
I currently have a table with a foreign key on it. I'm moving that foreign key to a related table:

```
Old:
TableA
 - fk_field  

New
TableB
 - table_a_id
 - fk_field
```

And I'm attempting this migration using the `forward` function in the migration

```
def forward(old_orm, new_orm):
    table_a = old_orm['tablea']
    table_b = new_orm['tableb']
    return [
        table_b.insert_from(
            table_a.select(
                table_a.id,
                table_a.fk_field
            ),
            fields=[
                table_b.table_a,
                table_b.fk_field
            ]
        ).execute()
    ]
```

But when I run `pem show` I get an error:
```
peewee.ProgrammingError: relation "table_b" does not exist
LINE 1: INSERT INTO "table_b" ("table_a_id", "fk_field...
```

As I can't find any documentation for how the `forward` function works, I could be completely missing something here! Please can you help me with how to migrate the data?

**Comment by RickMeasham** [comment]
As I thought about it, the error appears to be coming from the database. Which means the `forward` is being executed when I `pem watch` rather than just dumping the SQL.

Removing the `execute()` has fixed the problem.

Duh.

Leaving this here for anyone in the future

**Comment by aachurin** [comment]
Hi!

Yes, you should not use execute here. Result of forward function is a list of steps.
