### ISSUE TITLE
Rollback migration ?

### ISSUE THREAD

**Issue by Seluj78** [aachurin/peewee_migrations#26]
Hi,

I've just had a migration fail, still trying to figure out why., How can I rollback a failed migration that was in progress ?

**Comment by aachurin** [comment]
In postgres, migration is done in one transaction, unless --autocommit is specified.
In other databases this is not guaranteed (you need to look at the documentation for the database).
In this case, you can return the database to its original state only manually, or you can try to use --skip option (skip first N operations).

**Comment by Seluj78** [comment]
Hi, thanks for the reply ! In my case, I'm using a postgreSQL database. if I want to rollback then i'm stuck ?

**Comment by aachurin** [comment]
`pem show migration-id` to view list of operations which will be performed (forward or backward, depends on migration-id)
`pem migrate migration-id` to perform migration (forward or backward, depends on migration-id)
`pem migrate zero` to return to initial state

**Comment by Seluj78** [comment]
ah okay i see !! I'll try that and let you know, cheers!
