### ISSUE TITLE
Difference between serialized migrations ?

### ISSUE THREAD

**Issue by Seluj78** [aachurin/peewee_migrations#27]
Hi @aachurin,

Quick question, what is the difference between a seriealized and normal migration ?

**Comment by aachurin** [comment]
Hi!

"Normal" migrations is computed automaticaly.
"Serialized" migrations is a freezed state of automaticaly computed migrations.

**Comment by Seluj78** [comment]
Can you explain more please ?

**Comment by Seluj78** [comment]
Please ? :)

**Comment by aachurin** [comment]
"Normal" migrations is real-time computed (each time).
"Serialized" means state was saved and could not be changed.

**Comment by Seluj78** [comment]
Thank you ! 😊

**Comment by aachurin** [comment]
Serialized migrations is a list of concrete operations to migrate from saved point A to saved point B
Normal migrations is a list of computed operations to migrate from point A to point B (evaluated according to the state)
