### ISSUE TITLE
PEM crash on already done migration

### ISSUE THREAD

**Issue by Seluj78** [aachurin/peewee_migrations#28]
It seems that I have gotten in a loop where the `migratehistory` table hasn't been updated so `pem` still tries to run a migration already done so it fails with for example `column already added` etc... How can I fix this ? is there a skip failed ?

**Comment by aachurin** [comment]
maybe you should use --fake option?

**Comment by Seluj78** [comment]
Will it skip the failed migrations ?

**Comment by Seluj78** [comment]
Up :)

**Comment by Seluj78** [comment]
Actually on this issue, the way I found to solve it was just add an entry to the migration table :)

**Comment by aachurin** [comment]
The --fake option is used to skip previously completed steps
