### ISSUE TITLE
Skipping the first migration because that table already exists

### ISSUE THREAD

**Issue by savraj** [aachurin/peewee_migrations#31]
So I added peewee-migrations to a new project after the db was already set up.

`pem watch` immediately created a migration that was creating a fresh table for a model that was already present.

To work around this issue, I simply marked the first migration as done by adding a row in the migrations table for the first migration. Is that a recommended practice or is there a better way? Or should that not have happened and was there something wrong with my setup when that first migration was created?

**Comment by aachurin** [comment]
In general, this is not a normal situation. But there is a special --fake key for such cases.
It will work if your real db structure and the final migration state are the same.
