### ISSUE TITLE
Fails on lambda defaults

### ISSUE THREAD

**Issue by danohu** [aachurin/peewee_migrations#34]
Trying to run 'pem watch' on a model containing this column:

    created_at = DateTimeField(default=lambda: datetime.now(timezone.utc))

leads to 

`Migration error: invalid syntax (<string>, line 13)`

It works if I remove the default.
going through it in pdb, it seems that the lambda internally is converted to this form, which cannot be executed:

`created_at = DateTimeField(default=adastraeco.database.models.<lambda>`

**Comment by aachurin** [comment]
You need to replace the lambda with a regular function:
```
def now(): 
    return datetime.now(timezone.utc)
```

`created_at = DateTimeField(default=now)`

But it will be easier to use `created_at = DateTimeField(default=datetime.utcnow)`

**Comment by danohu** [comment]
Thanks for replying so fast, @aachurin !
