### ISSUE TITLE
Renaming a field does not work as expected.

### ISSUE THREAD

**Issue by kairichard** [aachurin/peewee_migrations#5]
Consider the following example:
```python
class Model(peewee.Model):
    field1 = peewee.CharField()
```
Run the migration 
```bash
pem watch && pem migrate
```
Since renaming does not work we do the following

```python
class Model(peewee.Model):
    field1 = peewee.CharField(column_name="field2")
```
create and run the migration
```bash
pem watch && pem migrate
```
And than change the model code to 
```python
class Model(peewee.Model):
    field2 = peewee.CharField()
```
Everything good so far, the problem starts when adding another migration, e.g.

```python
class Model(peewee.Model):
    field2 = peewee.CharField()
    field3 = peewee.CharField()
```
create and show the migration
```bash
pem watch && pem show

  SQL> ALTER TABLE `model` ADD COLUMN `field2` VARCHAR(40) []
  SQL> ALTER TABLE `model` DROP COLUMN `field2` []
  SQL> ALTER TABLE `model` MODIFY `field2` VARCHAR(40) NOT NULL []
```
Which of course will fails because `field2` is dropped.

The problem IMO is that `field2` is considered a new field, which it actually isn't. 
But I understand that I created the problem in the first place by renaming instead of adding and dropping the field - which actually we can't because we want to keep the data. 

What is the expected way to go forward?

**Comment by aachurin** [comment]
at the second step:

```python
class Model(peewee.Model):
    field2 = peewee.CharField()
```

then
```bash
pem watch
```

open migration file (in your case 0002_migration_....) and change `forward` and `backward` functions:
```python
def forward(old_orm, new_orm):
    model1 = new_orm['model1']
    return [
        # REMOVE THIS LINE: model1.update({model1.field2: 0}).where(model1.field2.is_null(True))
        model1.update({model1.field2: model1.field2.alias('field1')})
    ]


def backward(old_orm, new_orm):
    model1 = new_orm['model1']
    return [
        # REMOVE THIS LINE:  model1.update({model1.field1: 0}).where(model1.field1.is_null(True)),
        model1.update({model1.field1: model1.field1.alias('field2')})
    ]
```

And now you can run `migrate`

**Comment by kairichard** [comment]
I understand, thank you very much.
