### ISSUE TITLE
Running migrate without the CLI

### ISSUE THREAD

**Issue by RickMeasham** [aachurin/peewee_migrations#9]
Is it possible to run `pem migrate` from python rather than from the CLI? My database is in RDS with no public access so I'd love to be able to trigger a migration from Lambda.

**Comment by aachurin** [comment]
Try these code:

```
from peewee_migrations import cli
cli.main(args=["migrate"], standalone_mode=False)
```

**Comment by legioz** [comment]
> Try these code:
> 
> ```
> from peewee_migrations import cli
> cli.main(args=["migrate"], standalone_mode=False)
> ```

This is not working in the [latest version](https://pypi.org/project/peewee-migrations/0.3.32/)

Is there a workarround for the issue?
